version: '#{build}'
image:
  - Visual Studio 2017
environment:
  matrix:
    - node_js: '' # latest node
    - node_js: '12'
    - node_js: '10' # minimum
clone_depth: 5
skip_tags: true
build: off
matrix:
  fast_finish: true
  allow_failures:
    - node_js: ''
platform:
  - x64
cache:
  - node_modules
init:
  # Install the platform version of Node.js
  - ps: Install-Product node $env:node_js $env:platform
  # Output useful info for debugging
  - node --version
  - npm --version
  - yarn --version
  - ps: $PSVersionTable.PSVersion -f ''
install:
  - npm install
test_script:
  - npm test
