name: build

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} | ${{ matrix.os }} | ${{ matrix.arch }}

    timeout-minutes: 5

    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        # os:
        #   - ubuntu-latest
        #   - macOS-latest
        #   - windows-latest
        # arch:
        #   - x64
        # node-version:
        #   - 18
        # experimental:
        #   - false
        # send_coverage:
        #   - false
        include:
          - os: ubuntu-latest
            arch: x64
            node-version: 20 # latest
            experimental: true
            node_minimum: false
          - os: macOS-latest
            arch: x64
            node-version: 20 # latest
            experimental: true
            send_coverage: false
          - os: windows-latest
            arch: x64
            node-version: 20 # latest
            experimental: true
            send_coverage: false

          - os: ubuntu-latest
            node-version: 18 # minimum
            arch: x64
            experimental: false
            send_coverage: true
          - os: macOS-latest
            arch: x64
            node-version: 18 # minimum
            experimental: false
            send_coverage: false
          - os: windows-latest
            arch: x64
            node-version: 18 # minimum
            experimental: false
            send_coverage: false

    steps:
      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build info
        run: |
          node --version
          npm --version

      - name: Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Installing dependencies
        run: npm ci

      - name: Running tests
        continue-on-error: ${{ matrix.experimental }}
        run: npm test

      - name: Uploading code coverage report
        if: >
          (
            success() &&
            matrix.send_coverage &&
            github.event_name == 'push' &&
            github.repository_owner == 'JimiC' &&
            github.actor != 'dependabot[bot]'
          )
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Uploading code coverage artifact
        if: >
          (
            success() &&
            matrix.send_coverage &&
            github.event_name == 'pull_request' &&
            github.actor != 'dependabot[bot]'
          )
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/lcov.info
          retention-days: 1
