name: build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: 'Node.js: ${{ matrix.node-version }} | ${{ matrix.os }} | ${{ matrix.arch }}'

    timeout-minutes: 5

    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        node-version:
          - 16
        experimental: [false]
        minimum: [false]
        include:
          - os: ubuntu-latest
            arch: x64
            node-version: 18 # latest
            experimental: true
            minimum: false
          - os: macOS-latest
            arch: x64
            node-version: 18 # latest
            experimental: true
            minimum: false
          - os: windows-latest
            arch: x64
            node-version: 18 # latest
            experimental: true
            minimum: false

          - os: ubuntu-latest
            node-version: 14 # minimum
            arch: x64
            experimental: false
            minimum: true
          - os: macOS-latest
            arch: x64
            node-version: 14 # minimum
            experimental: false
            minimum: true
          - os: windows-latest
            arch: x64
            node-version: 14 # minimum
            experimental: false
            minimum: true

    steps:
      - name: Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Check concurrency
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: "Setting up Node.js: ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build info
        run: |
          node --version
          npm --version

      - name: Setting up coverage reporter
        if: (matrix.os == 'ubuntu-latest' && matrix.minimum)
        run: |
          curl -sL "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64" > cc-test-reporter
          chmod +x cc-test-reporter
          ./cc-test-reporter before-build

      - name: Installing dependencies
        run: npm ci

      - name: Running tests
        continue-on-error: ${{ matrix.experimental }}
        run: npm test

      - name: Test coverage report
        if: (success() && matrix.os == 'ubuntu-latest' && matrix.minimum)
        run: ./cc-test-reporter after-build -r ${{ secrets.CC_TEST_REPORTER_ID }}
