name: build

on:
  push:
    tags:
      - '!*'
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 'Node.js: ${{ matrix.node-version }} | ${{ matrix.os }} | ${{ matrix.arch }}'

    timeout-minutes: 5

    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        node-version:
          - 18
        experimental: [false]
        minimum: [false]
        include:
          - os: ubuntu-latest
            arch: x64
            node-version: 20 # latest
            experimental: true
            minimum: false
          - os: macOS-latest
            arch: x64
            node-version: 20 # latest
            experimental: true
            minimum: false
          - os: windows-latest
            arch: x64
            node-version: 20 # latest
            experimental: true
            minimum: false

          # - os: ubuntu-latest
          #   node-version: 18 # minimum
          #   arch: x64
          #   experimental: false
          #   minimum: true
          # - os: macOS-latest
          #   arch: x64
          #   node-version: 18 # minimum
          #   experimental: false
          #   minimum: true
          # - os: windows-latest
          #   arch: x64
          #   node-version: 18 # minimum
          #   experimental: false
          #   minimum: true

    steps:
      - name: Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Check concurrency
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: "Setting up Node.js: ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build info
        run: |
          node --version
          npm --version

      - name: Installing dependencies
        run: npm ci

      - name: Running tests
        continue-on-error: ${{ matrix.experimental }}
        run: npm test

      - name: Sending coverage report
        if: (success() && matrix.os == 'ubuntu-latest' && matrix.minimum && github.actor != 'dependabot[bot]' && github.repository_owner == 'JimiC')
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
