name: publish

on:
  push:
    tags: '*'

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: "Setting up Node.js: 14"
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build info
        run: |
          node --version
          npm --version

      - name: Installing dependencies
        run: npm ci

      - name: Publishing to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
